# General Jekyll Config
highlighter: pygments
url: http://baswenneker.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: kramdown

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#94243A' 

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: baswenneker
    #bitbucket: philipj
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    #twitter: _swanson
    #facebook: zuck
    #tumblr: animalygifs
    linkedin: baswenneker
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Bas Wenneker
  email: b.wenneker@gmail.com
  tagline: "weak opinions, strongly held"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-52648095-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
